In [1]:
import pandas as pd
import numpy as np 
import os
import pyreadr
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
person_wd = os.getcwd() + "\\AMELIA\\AMELIA_P_level_v0.2.3 (Person-Level)\\AMELIA_P_level_v0.2.3\\"
age = pyreadr.read_r(person_wd + "PAML.AGE_v0.2.3.RData")
df1 = age["AGE"]
BAS = pyreadr.read_r(person_wd + "PAML.BAS_v0.2.3.RData")
df1["Work_Status"] = BAS["BAS"]
CIT = pyreadr.read_r(person_wd + "PAML.CIT_v0.2.3.RData")
df1["City/Community"] = CIT["CIT"]
COB = pyreadr.read_r(person_wd + "PAML.COB_v0.2.3.RData")
df1["County_of_Birth"] = COB["COB"]
DIS = pyreadr.read_r(person_wd + "PAML.DIS_v0.2.3.RData")
df1["District"] = DIS["DIS"]
DOU = pyreadr.read_r(person_wd + "PAML.DOU_v0.2.3.RData")
df1["Degree_of_urbanisation"] = DOU["DOU"]
EDI = pyreadr.read_r(person_wd + "PAML.EDI_v0.2.3.RData")
df1["Equivalised_diposable_income(house-hold)"] = EDI["EDI"]
EDU = pyreadr.read_r(person_wd + "PAML.EDU_v0.2.3.RData")
df1["Current_Education_Activity"] = EDU["EDU"]
HHS = pyreadr.read_r(person_wd + "PAML.HHS_v0.2.3.RData")
df1["Household_size"] = HHS["HHS"]
HID = pyreadr.read_r(person_wd + "PAML.HID_v0.2.3.RData")
df1["Household_ID"] = HID["HID"]
INC = pyreadr.read_r(person_wd + "PAML.INC_v0.2.3.RData")
df1["Person_Income"] = INC["INC"]
ISCED = pyreadr.read_r(person_wd + "PAML.ISCED_v0.2.3.RData")
df1["Highest_ISCED"] = ISCED["ISCED"]
MST = pyreadr.read_r(person_wd + "PAML.MST_v0.2.3.RData")
df1["Martial_Status"] = MST["MST"]
PID = pyreadr.read_r(person_wd + "PAML.PID_v0.2.3.RData")
df1["Personal_ID"] = PID["PID"]
PROV = pyreadr.read_r(person_wd + "PAML.PROV_v0.2.3.RData")
df1["Province"] = PROV["PROV"]
PWHI = pyreadr.read_r(person_wd + "PAML.PWHI_v0.2.3.RData")
df1["Highest_Income_person"] = PWHI["PWHI"]
PY010 = pyreadr.read_r(person_wd + "PAML.PY010_v0.2.3.RData")
df1["Cash_Income"] = PY010["PY010"]
PY020 = pyreadr.read_r(person_wd + "PAML.PY020_v0.2.3.RData")
df1["Non-Cash_Employee"] = PY020["PY020"]
PY050 = pyreadr.read_r(person_wd + "PAML.PY050_v0.2.3.RData")
df1["Cash_Benefits_or_SE_loss"] = PY050["PY050"]
PY070 = pyreadr.read_r(person_wd + "PAML.PY070_v0.2.3.RData")
df1["Goods_Value_Produced_For_Own_Consumption"] = PY070["PY070"]
PY090 = pyreadr.read_r(person_wd + "PAML.PY090_v0.2.3.RData")
df1["Unemployment_Benfits"] = PY090["PY090"]
PY100 = pyreadr.read_r(person_wd + "PAML.PY100_v0.2.3.RData")
df1["Old-Age_Benefits"] = PY100["PY100"]
PY110 = pyreadr.read_r(person_wd + "PAML.PY110_v0.2.3.RData")
df1["Survivor_Benefits"] = PY110["PY110"]
PY120 = pyreadr.read_r(person_wd + "PAML.PY120_v0.2.3.RData")
df1["Sickness_Benefits"] = PY120["PY120"]
PY130 = pyreadr.read_r(person_wd + "PAML.PY130_v0.2.3.RData")
df1["Disability_Benefits"] = PY130["PY130"]
PY140 = pyreadr.read_r(person_wd + "PAML.PY140_v0.2.3.RData")
df1["Education-Related_Allowances"] = PY140["PY140"]
REG = pyreadr.read_r(person_wd + "PAML.REG_v0.2.3.RData")
df1["Regional_ID"] = REG["REG"]
RES = pyreadr.read_r(person_wd + "PAML.RES_v0.2.3.RData")
df1["Residential Status"] = RES["RES"]
SEM = pyreadr.read_r(person_wd + "PAML.SEM_v0.2.3.RData")
df1["Self_Employment_Dummy"] = SEM["SEM"]
SEX = pyreadr.read_r(person_wd + "PAML.SEX_v0.2.3.RData")
df1["Sex"] = SEX["SEX"]
SOC = pyreadr.read_r(person_wd + "PAML.SOC_v0.2.3.RData")
df1["Social_Income"] = SOC["SOC"]
SUP = pyreadr.read_r(person_wd + "PAML.SUP_v0.2.3.RData")
df1["Managerial_Position"] = SUP["SUP"]
UEP = pyreadr.read_r(person_wd + "PAML.UEP_v0.2.3.RData")
df1["Unemployment_Profile"] = UEP["UEP"]

In [351]:
#Narrow Dataset to only include individuals 18-65 years old
sex = {1:"Male",2:"Female"}
Trimmed_Age = df1.loc[(df1["AGE"] > 17) & (df1["AGE"] < 66)]
Trimmed_Age = Trimmed_Age.replace({"Sex": sex})

In [352]:
#Identify region Count
Check_Region = Trimmed_Age.groupby(["City/Community", "Province"]).size().reset_index().rename(columns={0:"Count"})

#Generate our Target and Class Dataframes for KNN
Target_list = Check_Region.loc[(Check_Region["Count"] < 300)]
Classes = Trimmed_Age.groupby(["City/Community", "Province"])["Person_Income"].agg(Person_Income='mean').reset_index().round(2)

#Create Dataframe for our Target Cities
Target = Classes.merge(Target_list, left_on='City/Community', right_on='City/Community').drop(columns="Province_y").rename(columns={"Province_x":"Province"})

#Remove Values to be reassigned from Classes Dataframe
Classes = Classes[~Classes.isin(Target_list)].dropna().reset_index()

In [271]:
"""INPUT (Dataframe: node's we want to find NN class, Dataframe: Classes for Comparison) RETURNS: Dictionary of {Node of Interest: Nearest Neighbour}"""
def KNN(Target, Classes):
    NN_dict = {} 
    #Iterates through the target list, grabbing the closest class neighbor in the province based on Income and returns the corresponding Neasrest Neighbour City/Community 
    for i in range(len(Target)):
        T_City = Target['City/Community'][i]
        NN = Classes.iloc[abs(Classes.loc[Classes['Province'] == Target['Province'][i]]['Person_Income'] - Target.iloc[i]['Person_Income']).idxmin(axis=0)]['City/Community']
        NN_dict[T_City] = round(NN)
    return NN_dict

Redistribution = KNN(Target,Classes)

In [442]:
#Create a Dictionary for redistricting Cities/Communities that have been changed
Districts = Trimmed_Age.groupby(['City/Community', 'District']).size().reset_index()
Districts = dict(zip(Districts['City/Community'], Districts['District']))
Redistrict = {}
for k,v in Redistribution.items():
    if Districts[k] != Districts[v]:
        Redistrict[k] = Districts[v]

In [446]:
#District Reassignment (Pandas has forced my hand, because replace doesn't work, this must be done)
for k,v in Redistrict.items():
    Trimmed_Age.loc[Trimmed_Age['City/Community'] == k, 'District'] = v

#City/Community Reassignment 
for k,v in Redistribution.items():
    Trimmed_Age.loc[Trimmed_Age['City/Community'] == k, 'City/Community'] = v

In [447]:
#Check to ensure all Cities/Communities have been reassigned
Trimmed_Age.groupby(["City/Community", "Province", 'District']).size().reset_index().rename(columns={0:"Count"})

      City/Community  Province  District  Count
0                  6         1         3    361
1                  9         1         3    440
2                 11         1         3    510
3                 14         1         3    578
4                 15         1         3    553
...              ...       ...       ...    ...
1534            1588        11        40   3517
1535            1589        11        40   7889
1536            1590        11        40   2619
1537            1591        11        40   1341
1538            1592        11        40   6142

[1539 rows x 4 columns]

In [448]:
#Export to CSV file
# Trimmed_Age.to_csv('Cleaned_Amelia_Dataset.csv')